{
 "title": "croiscendence's cAdvisor",
 "description": "croiscendence's cAdvisor Dashboard for Docker container",
 "tags": [
  "cAdvisor",
  "Docker"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": "cAdvisor" },
   { "name": "Metrics", "label": "Metrics", "query": "Docker" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Croiscendence 🥐",
   "type": "text",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 1 },
   "options": {
    "content": "# cAdvisor Dashboard\n\nThis is dashboard for Docker metrics\n\nNumber of services: 6\n\n  - Backend: 3000 (https)\n  - Prometheus: 9090\n  - Grafana: 3003 (https)\n  - Nodejs Exporter: 9101\n  - cAdvisor: 8080\n  - AlertManager: 9093"
   }
  },
  {
   "title": "Docker CPU Usage General",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total[$__rate_interval])) * 100",
     "legendFormat": "host"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{id!=\"/\"}[$__rate_interval])) by (id)",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{id=\"/\"}[$__rate_interval])) by (id)",
     "legendFormat": "SENT"
    }
   ]
  },
  { "title": "Container CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "CPU Usage (%) per Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{cpu=\"total\", id!=\"/\"}[1m]) * 100",
     "legendFormat": "{{id}}"
    }
   ]
  },
  { "title": "Container Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Memory Usage (bytes) Per Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{id!=\"/\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  { "title": "Container Disk IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Disk Read (bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "rate(container_fs_reads_bytes_total{id!=\"/\"}[1m])",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Disk Write (bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "rate(container_fs_writes_bytes_total{id!=\"/\"}[1m])",
     "legendFormat": "{{id}}"
    }
   ]
  },
  { "title": "Container Metadata", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Container Restarts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "container_start_time_seconds", "legendFormat": "{{id}}" }
   ]
  },
  {
   "title": "Container Uptime (seconds)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{id!=\"/\"}",
     "legendFormat": "{{id}}"
    }
   ]
  }
 ]
}