{
 "title": "Prometheus Metrics Dashboard Full",
 "description": "Almost all internal Prometheus metrics",
 "tags": [ "prometheus" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(prometheus_build_info, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Prometheus Ready",
   "type": "stat",
   "description": "Whether Prometheus startup was fully completed and the server is ready for normal operation.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_ready{instance=\"$instance\"}",
     "legendFormat": "{{ instance }} {{job}}"
    }
   ]
  },
  {
   "title": "Configuration Reload",
   "type": "stat",
   "description": "Whether the last configuration reload attempt was successful.",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_config_last_reload_successful{instance=\"$instance\"}",
     "legendFormat": "{{ instance }} {{job}}"
    }
   ]
  },
  {
   "title": "Targets",
   "type": "stat",
   "description": "Number of scrape pool targets.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prometheus_target_scrape_pool_targets{instance=\"$instance\"})",
     "legendFormat": "Total Targets"
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "stat",
   "description": "Total user and system CPU time.",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Active Alertmanagers",
   "type": "stat",
   "description": "The number of alertmanagers discovered and active.",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_notifications_alertmanagers_discovered{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Rule Execution",
   "type": "stat",
   "description": "The maximum p99 duration for a rule to execute.",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "prometheus_rule_evaluation_duration_seconds{instance=\"$instance\",quantile=\"0.99\"}",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "Oldest Value",
   "type": "stat",
   "description": "Oldest timestamp value stored in the database.",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "timestamp(prometheus_tsdb_lowest_timestamp_seconds)-prometheus_tsdb_lowest_timestamp_seconds{instance=\"$instance\"}",
     "legendFormat": "Total Targets"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "stat",
   "description": "Number of open file descriptors.",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_fds{instance=\"$instance\"}",
     "legendFormat": "Open"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_build_info{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query Log",
   "type": "stat",
   "description": "State of the query log.\nhttps://prometheus.io/docs/guides/query-log/",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_engine_query_log_enabled{instance=\"$instance\"}",
     "legendFormat": "{{ instance }} {{job}}"
    }
   ]
  },
  {
   "title": "Process Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"prometheus\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Configuration Reload Time",
   "type": "stat",
   "description": "Last successful configuration reload.",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - prometheus_config_last_reload_success_timestamp_seconds{job=\"prometheus\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Local Storage",
   "type": "stat",
   "description": "The number of bytes that are currently used for local storage by all blocks.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_tsdb_storage_blocks_bytes{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "stat",
   "description": "Resident memory size.",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Sent Alerts [10m]",
   "type": "stat",
   "description": "Total number of alerts sent.",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prometheus_notifications_sent_total{instance=\"$instance\"}[10m]))",
     "legendFormat": "{{alertmanager}}"
    }
   ]
  },
  {
   "title": "Rule Group Evaluation",
   "type": "stat",
   "description": "The maximum p99 duration of rule group evaluations.",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "prometheus_rule_group_duration_seconds{instance=\"$instance\",quantile=\"0.99\"}",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "Active Queries",
   "type": "stat",
   "description": "The current number of queries being executed or waiting.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_engine_queries{instance=\"$instance\"}",
     "legendFormat": "active"
    }
   ]
  },
  {
   "title": "Log Failures",
   "type": "stat",
   "description": "The number of query log failures.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(prometheus_engine_query_log_failures_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Open"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Sent Alerts [10m]",
   "type": "timeseries",
   "description": "Total number of alerts sent in 10 minutes periods.",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(prometheus_notifications_sent_total{instance=\"$instance\"}[10m])",
     "legendFormat": "{{alertmanager}}"
    }
   ]
  },
  {
   "title": "Active Alertmanagers",
   "type": "stat",
   "description": "The number of alertmanagers discovered and active.",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_notifications_alertmanagers_discovered{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Notification Queue",
   "type": "stat",
   "description": "The number of alert notifications in the queue.",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_notifications_queue_length{instance=\"$instance\"}",
     "legendFormat": "Queue Length"
    }
   ]
  },
  {
   "title": "Alert Errors",
   "type": "stat",
   "description": "Errors sending alert notifications.",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prometheus_notifications_errors_total{instance=\"$instance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Template Expansions",
   "type": "stat",
   "description": "The total number of template text expansions.",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(prometheus_template_text_expansions_total{instance=\"$instance\"}[$__range])",
     "legendFormat": "Queue Length"
    }
   ]
  },
  {
   "title": "Template Failures",
   "type": "stat",
   "description": "The total number of template text expansion failures.",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(prometheus_template_text_expansion_failures_total{instance=\"$instance\"}[$__range])",
     "legendFormat": "Queue Length"
    }
   ]
  },
  {
   "title": "Dropped Alerts",
   "type": "stat",
   "description": "Alerts dropped due to errors when sending to Alertmanager.",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(prometheus_notifications_dropped_total{instance=\"$instance\"}[$__range])"
    }
   ]
  },
  { "title": "Rule Evaluation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Rule Execution Time",
   "type": "timeseries",
   "description": "The duration for a rule to execute.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "prometheus_rule_evaluation_duration_seconds{instance=\"$instance\"}",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "Rule Group Evaluation Time",
   "type": "timeseries",
   "description": "The duration of rule group evaluations.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "prometheus_rule_group_duration_seconds{instance=\"$instance\"}",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "Rule Groups",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "prometheus_rule_group_rules{instance=\"$instance\"}",
     "legendFormat": "# of rules"
    },
    {
     "expr": "prometheus_rule_group_last_evaluation_samples{instance=\"$instance\"}",
     "legendFormat": "Samples"
    },
    {
     "expr": "prometheus_rule_group_last_duration_seconds{instance=\"$instance\"}",
     "legendFormat": "Last duration"
    },
    {
     "expr": "increase(prometheus_rule_group_iterations_total{instance=\"$instance\"}[$__range])",
     "legendFormat": "Iterations"
    },
    {
     "expr": "prometheus_rule_group_interval_seconds{instance=\"$instance\"}",
     "legendFormat": "Interval"
    },
    {
     "expr": "increase(prometheus_rule_group_iterations_missed_total{instance=\"$instance\"}[$__range])",
     "legendFormat": "Missed"
    },
    {
     "expr": "increase(prometheus_rule_evaluations_total{instance=\"$instance\"}[$__range])",
     "legendFormat": "Rule Evaluations"
    },
    {
     "expr": "increase(prometheus_rule_evaluation_failures_total{instance=\"$instance\"}[$__range])",
     "legendFormat": "Failed Evaluations"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query Duration (p90)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "prometheus_engine_query_duration_seconds{instance=\"$instance\",quantile=\"0.9\"}",
       "legendFormat": "{{slice}}"
      }
     ]
    },
    {
     "title": "Query Duration (p99)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "prometheus_engine_query_duration_seconds{instance=\"$instance\",quantile=\"0.99\"}",
       "legendFormat": "{{slice}}"
      }
     ]
    },
    {
     "title": "HTTP Latency (/metrics)",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 81 },
     "targets": [
      {
       "expr": "sum(increase(prometheus_http_request_duration_seconds_bucket{instance=\"$instance\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Response Size (/metrics)",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 81 },
     "targets": [
      {
       "expr": "sum(increase(prometheus_http_response_size_bytes_bucket{instance=\"$instance\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Incoming Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Accepted Connections",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3008 },
     "targets": [
      {
       "expr": "rate(net_conntrack_listener_conn_accepted_total{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{listener_name}}"
      }
     ]
    },
    {
     "title": "Listener Closed Connections",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3008 },
     "targets": [
      {
       "expr": "rate(net_conntrack_listener_conn_closed_total{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{listener_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Outgoing Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Established Connections",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3342 },
     "targets": [
      {
       "expr": "rate(net_conntrack_dialer_conn_established_total{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{dialer_name}}"
      }
     ]
    },
    {
     "title": "Connection Attempts",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3342 },
     "targets": [
      {
       "expr": "rate(net_conntrack_dialer_conn_attempted_total{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{dialer_name}}"
      }
     ]
    },
    {
     "title": "Refused Connections",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3352 },
     "targets": [
      {
       "expr": "rate(net_conntrack_dialer_conn_failed_total{instance=\"$instance\",reason=\"refused\"}[$__rate_interval])",
       "legendFormat": "{{dialer_name}}"
      }
     ]
    },
    {
     "title": "Closed Connections",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3352 },
     "targets": [
      {
       "expr": "rate(net_conntrack_dialer_conn_closed_total{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{dialer_name}}"
      }
     ]
    },
    {
     "title": "Resolution Failures",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3362 },
     "targets": [
      {
       "expr": "rate(net_conntrack_dialer_conn_failed_total{instance=\"$instance\",reason=\"resolution\"}[$__rate_interval])",
       "legendFormat": "{{dialer_name}}"
      }
     ]
    },
    {
     "title": "Timed-out Connections",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3362 },
     "targets": [
      {
       "expr": "rate(net_conntrack_dialer_conn_failed_total{instance=\"$instance\",reason=\"timeout\"}[$__rate_interval])",
       "legendFormat": "{{dialer_name}}"
      }
     ]
    },
    {
     "title": "Unknown Connection Failures",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3372 },
     "targets": [
      {
       "expr": "rate(net_conntrack_dialer_conn_failed_total{instance=\"$instance\",reason=\"unknown\"}[$__rate_interval])",
       "legendFormat": "{{dialer_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU / Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prometheus CPU Usage %",
     "type": "timeseries",
     "description": "Total user and system CPU time of Prometheus process.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Prometheus RAM Usage",
     "type": "timeseries",
     "description": "Resident memory size of Prometheus process",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{instance=\"$instance\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Head Block",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "# of Series",
     "type": "timeseries",
     "description": "Total number of series in the head block.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "prometheus_tsdb_head_series{instance=\"$instance\"}",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Series Churn",
     "type": "timeseries",
     "description": "Total number of series created/removed in the head",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_head_series_created_total{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "created"
      },
      {
       "expr": "rate(prometheus_tsdb_head_series_removed_total{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "removed"
      }
     ]
    },
    {
     "title": "Time Bounds",
     "type": "timeseries",
     "description": "Minumum and maximum timestamp of the head block.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "timestamp(prometheus_tsdb_head_max_time_seconds{instance=\"$instance\"})-prometheus_tsdb_head_max_time_seconds{instance=\"$instance\"}",
       "legendFormat": "max"
      },
      {
       "expr": "timestamp(prometheus_tsdb_head_min_time_seconds{instance=\"$instance\"})-prometheus_tsdb_head_min_time_seconds{instance=\"$instance\"}",
       "legendFormat": "min"
      }
     ]
    },
    {
     "title": "Samples Appended",
     "type": "timeseries",
     "description": "Total number of appended samples.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_head_samples_appended_total{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Chunks in Head",
     "type": "timeseries",
     "description": "Total number of chunks in the head block.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "prometheus_tsdb_head_chunks{instance=\"$instance\"}",
       "legendFormat": "chunks"
      }
     ]
    },
    {
     "title": "Chunks Churn",
     "type": "timeseries",
     "description": "Total number of chunks created/removed in the head",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_head_chunks_created_total{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "created"
      },
      {
       "expr": "rate(prometheus_tsdb_head_chunks_removed_total{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "removed"
      }
     ]
    },
    {
     "title": "Active Appenders",
     "type": "timeseries",
     "description": "Number of currently active appender transactions.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
     "targets": [
      {
       "expr": "prometheus_tsdb_head_active_appenders{instance=\"$instance\"}",
       "legendFormat": "active appenders"
      }
     ]
    },
    {
     "title": "Truncations",
     "type": "stat",
     "description": "Total number of head truncations attempted.",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 93 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_head_truncations_total{instance=\"$instance\"}[$__range])",
       "legendFormat": "Samples OOO"
      }
     ]
    },
    {
     "title": "Failed Truncations",
     "type": "stat",
     "description": "Total number of head truncations that failed.",
     "gridPos": { "h": 5, "w": 3, "x": 15, "y": 93 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_head_truncations_failed_total{instance=\"$instance\"}[$__range])",
       "legendFormat": "Samples OOO"
      }
     ]
    },
    {
     "title": "Series Not Found",
     "type": "stat",
     "description": "Total number of requests for series that were not found.",
     "gridPos": { "h": 5, "w": 3, "x": 18, "y": 93 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_head_series_not_found_total{instance=\"$instance\"}[$__range])",
       "legendFormat": "Samples OOO"
      }
     ]
    },
    {
     "title": "Samples Out of Order",
     "type": "stat",
     "description": "Total number of appended out of order samples.",
     "gridPos": { "h": 5, "w": 3, "x": 21, "y": 93 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_head_out_of_order_samples_appended_total{instance=\"$instance\"}[$__range])",
       "legendFormat": "Samples OOO"
      }
     ]
    }
   ]
  },
  {
   "title": "Scrape",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Targets per Job",
     "type": "stat",
     "description": "Current number of targets in this scrape pool.",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prometheus_target_scrape_pool_targets{instance=\"$instance\"}",
       "legendFormat": "{{ scrape_job }}"
      }
     ]
    },
    {
     "title": "Actual Intervals between Scrapes (p99)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prometheus_target_interval_length_seconds{instance=\"$instance\",quantile=\"0.99\"}",
       "legendFormat": "{{ interval }}"
      }
     ]
    },
    {
     "title": "Sync Interval",
     "type": "timeseries",
     "description": "Actual interval to sync the scrape pool.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "prometheus_target_sync_length_seconds{instance=\"$instance\",quantile=\"0.99\"}",
       "legendFormat": "{{scrape_job}}"
      }
     ]
    },
    {
     "title": "Duplicate Rejected",
     "type": "stat",
     "description": "Total number of samples rejected due to duplicate timestamps but different values.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 84 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(prometheus_target_scrapes_sample_duplicate_timestamp_total{instance=\"$instance\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Samples Out of Order",
     "type": "stat",
     "description": "Total number of samples rejected due to not being out of the expected order.",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 84 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(prometheus_target_scrapes_sample_out_of_order_total{instance=\"$instance\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Exemplars Out of Order",
     "type": "stat",
     "description": "Total number of exemplar rejected due to not being out of the expected order.",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 84 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(prometheus_target_scrapes_exemplar_out_of_order_total{instance=\"$instance\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Pool Creation Attempts",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 84 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(prometheus_target_scrape_pools_total{instance=\"$instance\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Pool Reloads",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 84 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(prometheus_target_scrape_pool_reloads_total{instance=\"$instance\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Sample Limit Hits",
     "type": "stat",
     "description": "Total number of scrapes that hit the sample limit and were rejected.",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 84 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(prometheus_target_scrapes_exceeded_sample_limit_total{instance=\"$instance\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Label Limit Hits",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 84 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(prometheus_target_scrape_pool_exceeded_label_limits_total{instance=\"$instance\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Metadata Cache",
     "type": "stat",
     "description": "Metric metadata in the cache for target scraping.",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(prometheus_target_metadata_cache_bytes{instance=\"$instance\"})",
       "legendFormat": "{{scrape_job}}"
      }
     ]
    },
    {
     "title": "Cache Force Flushes",
     "type": "stat",
     "description": "How many times a scrape cache was flushed due to getting big while scrapes are failing.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 88 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(prometheus_target_scrapes_cache_flush_forced_total{instance=\"$instance\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Samples Out of Bounds",
     "type": "stat",
     "description": "Total number of samples rejected due to timestamp falling outside of the time bounds.",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 88 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(prometheus_target_scrapes_sample_out_of_bounds_total{instance=\"$instance\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Target Sync Failure",
     "type": "stat",
     "description": "Total number of target sync failures.",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 88 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(prometheus_target_sync_failed_total{instance=\"$instance\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Pool Creation Failures",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 88 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(prometheus_target_scrape_pools_failed_total{instance=\"$instance\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Pool Reload Failures",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 88 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(prometheus_target_scrape_pool_reloads_failed_total{instance=\"$instance\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Body Size Limit Hits",
     "type": "stat",
     "description": "Total number of scrapes that hit the body size limit",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 88 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(prometheus_target_scrapes_exceeded_body_size_limit_total{instance=\"$instance\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Target Limit Hits",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 88 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(prometheus_target_scrape_pool_exceeded_target_limit_total{instance=\"$instance\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Pool Syncs",
     "type": "stat",
     "description": "Average number syncs executed on scrape pools between all jobs.",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 88 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(increase(prometheus_target_scrape_pool_sync_total{instance=\"$instance\"}[$__range]))"
      }
     ]
    }
   ]
  }
 ]
}